apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-churn-app
  labels:
    app: customer-churn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-churn
  template:
    metadata:
      labels:
        app: customer-churn
    spec:
      containers:
      - name: customer-churn
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: PORT
          value: "8000"