apiVersion: v1
kind: Service
metadata:
  name: customer-churn-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb         
spec:
  type: LoadBalancer
  selector:
    app: customer-churn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
